### PR TITLE
Add signup section

### PR DESCRIPTION
**Pull request by jtr13**

### CODE REVIEW

**Comment by zachbogart** [comment]
Looks good to me.

**Comment by jtr13** [comment]
We'll see if Sir Travis agrees.

**Comment by zachbogart** [comment]
It should since it just built the changes and they passed. Also, if you are adding a new chapter, make sure you edit the bookdown.yml file and the DESCRIPTION files so that Travis runs your PR incorporating your new chapter into the book. Not applicable here, but good to do in certain cases.

**Comment by zachbogart** [comment]
Just passed: https://edav.info/project.html

**Comment by jtr13** [comment]
Woohoo.

**Comment by jtr13** [comment]
Yes, absolutely re: DESCRIPTION and bookdown.yml

**Pull request merged**
