### PR TITLE
maps chapter

### PR DESCRIPTION
**Pull request by zachbogart**
Hookup packages and try to run on Travis

### CODE REVIEW

**Comment by zachbogart** [comment]
Looks like a package called `units` is involved with the error.

**Comment by jtr13** [comment]
Right. Do you happen to have a link to the specific Travis fail? I will ask the statebins author what the deal is.

**Comment by zachbogart** [comment]
https://travis-ci.org/jtr13/EDAV/builds/445305240?utm_source=github_status&utm_medium=notification

For future reference, you can click on the "Show all checks" to see the Travis run and click "Details" to see the relevant Travis build. Clicking on the Travis logo will take you to the main page, which could also get you there with extra clicking.

**Comment by jtr13** [comment]
So units is a dependency of sf which is a dependency of choroplethr. So state in’s isn’t involved.

**Comment by zachbogart** [comment]
So maybe we could try installing sf formally in the DESCRIPTION file. Btw, everything is currently being installed from CRAN, so if that becomes a factor, we would have to look into how to ddownload from other sources.

The second plot seems to work for me, but the first one is where Travis and I stumble.

**Comment by jtr13** [comment]
The remotes section of DESCRIPTION is for other sources

**Comment by jtr13** [comment]
Btw units is difficult: https://stackoverflow.com/questions/42287164/install-udunits2-package-for-r3-3

**Comment by jtr13** [comment]
Passed... woot woot! Needed to add some stuff to .travis.yml

**Pull request merged**
