### PR TITLE
Delete some lines

### PR DESCRIPTION
**Pull request by jtr13**
Testing Travis.

### CODE REVIEW

**Comment by zachbogart** [comment]
You may consider updating the bookdown.yml to check travis will build the whole new book with your addition.

**Comment by jtr13** [comment]
I can't do that with this file since it's not ready to go in the book yet. As soon as I have it ready, I will modify bookdown.yml with the new chapter.  What's happening with the maps chapter? Where is Travis getting stuck?

**Comment by zachbogart** [comment]
I will make a pull request and see how it fares.

**Comment by zachbogart** [comment]
I think I will close this PR since the cleveland plot needs further fleshing out.

**Pull request closed without merging**
