### PR TITLE
missing comma

### PR DESCRIPTION
**Pull request by jtr13**
There was a problem in DESCRIPTION. Maybe that's it.  I don't like that GitHub is merging the pull requests before the Travis check has passed... was it always working that way?

### CODE REVIEW

**Comment by zachbogart** [comment]
This was the thing that making it build the pull requests makes the changes go live before merging

**Comment by jtr13** [comment]
Right. So this is the lesser of the two evils.

**Comment by zachbogart** [comment]
Something is broken. Travis is not being triggered when the changed are merged with master.

**Comment by zachbogart** [comment]
Maybe we should find some time to chat about this. Something has changed with regards to Travis since you added the maps chapter. I tried to push a small change directly to master and it no longer triggers a build.

**Comment by jtr13** [comment]
Sure, I'm available this afternoon if you have anytime, feel free to call or stop by (just let me know).  I didn't change any Travis settings and didn't touch the `.travis.yml` file so I have a feeling this is a Travis issue.  See here for example: https://stackoverflow.com/questions/28098907/why-is-my-travis-build-not-starting

**Comment by zachbogart** [comment]
The Travis thing will resolve eventually. Turns out Github is having an outage and they are working to remedy it. I'm gonna trigger a build and see how it does (if we can get to executing the code rather than just setting up the environment. 

https://www.traviscistatus.com/

**Comment by jtr13** [comment]
Aha. Makes sense: with one file and about 3 settings that we can alter it was hard to see how we could have caused this.

**Comment by jtr13** [comment]
I see it failed again.  It's coming up with "Error: Unknown remote type: github". Might not be related to the outage but probably best to wait until that's resolved to see what's what.

**Pull request merged**
