### PR TITLE
Adding grouped bar charts, stacked bar chart and diverging bar charts.

### PR DESCRIPTION
**Pull request by ankitaa06**
@zachbogart Please review it and help me know your suggestions/changes.

### CODE REVIEW

**Comment by ankitaa06** [comment]
@zachbogart How do I install any package to travis? travis build is giving an error because 
 "HH" package is not installed.

**Comment by zachbogart** [comment]
There is a file called DESCRIPTION. please add the desired package in alphabetical order to that file. Don't forget the comma.

**Comment by ankitaa06** [comment]
@zachbogart There is an error in installing the package 'rmpfr'. I am not sure why this package is being installed (maybe as a dependency to my additional 'HH' package). The fix for this is to run the following command:
sudo apt-get install libmpfr-dev

Not sure, how to proceed about the same.

https://stackoverflow.com/questions/31311050/r-package-rmpfr
https://stackoverflow.com/questions/33750315/installation-of-package-rmpfr-had-non-zero-exit-status

**Comment by jtr13** [comment]
@zachbogart If this is indeed the problem, then the fix will probably involve adding a line to the addons section of .travis.yml, based on this model: https://juliasilge.com/blog/beginners-guide-to-travis/

**Pull request closed without merging**
