### PR TITLE
Travis revert, new settings

### PR DESCRIPTION
**Pull request by zachbogart**
Okay. Try this again. Now switched off pull request builds.

### CODE REVIEW

**Comment by zachbogart** [comment]
Okay, that works. You can see if Travis is angry when you push your branch, but a pull request will not re-build the site. I think since we are doing a trick with gh-pages, the pull request is able to push changes to gh-pages where a branch isn't.

**Comment by zachbogart** [comment]
So I think this problem was always present, just not diagnosed. Now travis shouldn't affect the site until the pull request is merged with master.

**Comment by jtr13** [comment]
Awesome.  What did you change? Should I test it doing the same thing I did last time (local change to branch, push, submit pull request?) I see that "Build Pushed Branches" is still on... that makes me nervous.

**Comment by zachbogart** [comment]
Also, it looks like people are using it and liking the experience. People who stopped by office hours thanked me for putting it together. So, it seems to have been immediately beneficial for people. 

:)

**Pull request merged**
