### PR TITLE
add Handling Missing Values page

### PR DESCRIPTION
**Pull request by ujjwal95**
I have added a handling_nas.Rmd file for Missing Values handling.
I have added code from the lecture as well as some of my own experiences.

### CODE REVIEW

**Comment by zachbogart** [comment]
Please remove .DS_store from the PR.

**Comment by ujjwal95** [comment]
I have removed the .DS_Store file.

**Comment by zachbogart** [comment]
I'm trying to add some commits to your work. On the sidebar of this PR, you should see a checkbox to "Allow edits from maintainers". Let me know if it is visible and please check it.

**Comment by ujjwal95** [comment]
Yes, it is visible and I have already checked it.

**Comment by zachbogart** [comment]
The code seems to fail in your code chunk of a missing data plot where label=comma. Can you explain what you are intending this label to accomplish?

**Comment by ujjwal95** [comment]
The problem is that I did not import the 'scales' library. Importing that in the start of the code should resolve this issue.

**Comment by ujjwal95** [comment]
Thanks a lot Zach!

**Pull request merged**
