### PR TITLE
add maps.Rmd + banner

### PR DESCRIPTION
**Pull request by jtr13**
Note: I left the "under construction" message but took out the banner since it seemed a bit overwhelming.

### CODE REVIEW

**Comment by zachbogart** [comment]
Make sure to include new packages in the DESCRIPTION file. Also, I am having trouble getting the choroplethr package to work because of a "sf" dependency.

**Comment by jtr13** [comment]
Ok, good to know. What if packages (such as statebins) need to be installed from GitHub? Can Travis handle that?

**Comment by jtr13** [comment]
Re: sf  Try installing "choroplethrMaps" as well. That might be the problem.

**Comment by zachbogart** [comment]
Do you have a package called rgdal installed? That might be a necessary dependency.

**Comment by jtr13** [comment]
Yes, I do. If it is a necessary dependency, odd that it doesn't get installed with choroplethr. That seems to be the way things are done now.

**Comment by zachbogart** [comment]
Did you remember finding yourself installing things in this way:
https://github.com/r-spatial/sf

**Comment by zachbogart** [comment]
- Also, I tried to run the second plot and it is saying "show_guide" has been deprecated (related to the "theme_statebins()). 
- Make sure the final code chunk ends with triple backticks

**Comment by jtr13** [comment]
If you install `choroplethrMaps` you won't get the problems with all the other packages, such as `rgdal`, `sf`, etc.

I was getting the `show_guide` message but it stopped... not sure why.  It has to do with a change in ggplot2: https://blog.rstudio.com/2015/12/21/ggplot2-2-0-0/   Are you installing `statebins` from GitHub?

**Comment by zachbogart** [comment]
I just tried devtools installation for `statebins` and I'm having trouble. I'm running Mac OS Majoave, which might factor in to the hurdles. Can the choropleth plot be done just with `choroplethrMaps`?

**Comment by jtr13** [comment]
No... the choropleth requires both packages.  Perhaps try updating all your packages with update.packages() -- that often fixes a lot of problems. Given these troubles, we should include a list of the versions of packages used to build the book as they've done in the R 4 Data Science intro: http://r4ds.had.co.nz/introduction.html

**Comment by jtr13** [comment]
Any thoughts about what to do here? Shall we see if it works on Travis?

**Comment by zachbogart** [comment]
We can see how Travis handles it. You should update the DESCRIPTION file with the packages needed.

**Comment by jtr13** [comment]
I did... also alphabetized the file.

**Comment by zachbogart** [comment]
Did you modify the Travis backend? the repo seems to be turned off.

**Comment by zachbogart** [comment]
Actually it is on, but it was not activated when merged with master.

**Comment by jtr13** [comment]
Weird... is there a delay sometimes? Of course you can give it a kick to get going but that shouldn't be necessary.

**Comment by jtr13** [comment]
Interesting... I see the "Pull request successfully merged and closed: You’re all set—the Joyce branch can be safely deleted"  message but Travis is still working.  I somehow that the merge would fail if Travis failed.

**Comment by zachbogart** [comment]
It's failing to install something I think:
https://travis-ci.org/jtr13/EDAV/builds/444614040

**Pull request merged**
