### PR TITLE
Change subtitles, minor edits

### PR DESCRIPTION
**Pull request by jtr13**
Made some changes on a new branch

### CODE REVIEW

**Comment by zachbogart** [comment]
Did you already merge this with gh-pages? You proposed changes are already live on the site, but they aren't on master (might have been me doing something, but it's tough to tell).

**Comment by jtr13** [comment]
Oh, that's weird.  Why is that happening? Maybe it's doing an automatic merge from Joyce -> Master?

**Comment by zachbogart** [comment]
I think I got it. Travis right now runs if anything is pushed: branches or pull requests. I think pushing your branch caused Travis to run on your branch and overwrite gh-pages. But I'm not sure why, since I think I've done this before and it wasn't overwriting things.

**Comment by jtr13** [comment]
Aha. That makes sense. Before I was making changes on github.com to master and then clicking "Create a new branch for this commit and start a pull request."  This time I made the changes locally on a new branch, committed, and then pushed the commit. Later I made the pull request.  Is there a way to tell Travis to chill? :-)

**Comment by zachbogart** [comment]
Here's what I'm gonna do. I'm going to merge your changes from Joyce branch (fine changes) and close this pull request to get us back to normal. Travis has a setting to run if any branches or pull requests are pushed. I'm gonna try to shut those off and see if that fixes the problem.

**Comment by jtr13** [comment]
Sounds good.  Logically it doesn't make sense for Travis to bypass master and update edav.info from a branch. Btw, is there a link to see what's happening on gh-pages?

**Comment by jtr13** [comment]
Lmk when it's ok to make more changes.  I want to add code examples for the histogram types.

**Comment by zachbogart** [comment]
You can pick gh-pages as a dropdown from the main repo page. But it is a little cryptic since Travis uses my credentials under the hood so it always says that I updated the book.

**Comment by jtr13** [comment]
It looks to me like the Travis Bot (Berlin) updated, which is indeed what happened.  Whatever the Travis settings are, it seems very odd (read: bug) that gh-pages can be updated directly from a branch--I don't see why anyone would ever want that to happen.

**Pull request merged**
