### PR TITLE
Fixed broken links and "subtle" link issues

### PR DESCRIPTION
**Pull request by timjaya**
Fixed broken links and subtle link issues as described in: https://github.com/jtr13/EDAV/issues/109. 

The following are the broken links (found with https://www.brokenlinkcheck.com/broken-links.php#status):
1. https://edav.info/histogram.html at https://edav.info/box.html
2. https://www.datacamp.com/instructors/rickscavetta at https://edav.info/iris.html

The following are the links with the subtle issues (found with scrapy):
1. "https://dev.to/rly" at "/basics.html".
2. "basics.html#communicating-results" at "/iris.html"
3. "https://giphy.com/gifs/warnerarchive-classic-film-warner-archive-l0MYOUI5XfRk4LLWM" at "/contribute.html"
4. "https://giphy.com/gifs/reaction-food-simpsons-nxscd2YGVf6xi" at "/contribute.html"}
5. "https://datastorm-open.github.io/visNetwork/" at "/network.html"}
6. "https://github.com/settings/tokens" at "/publish.html"

Also added said web crawler that helps identifying subtle link issues in another branch. Documentation to install and run is included.

### CODE REVIEW

**Comment by zachbogart** [comment]
Nicely done! 

Could you remove any unnecessary files from the linechecker (DS_Store, etc.)?

**Comment by TimKartawijaya** [comment]
Just did! I removed the DS_Store and .pyc bin files.

**Comment by zachbogart** [comment]
There's another DS_Store in your main directory.

**Comment by zachbogart** [comment]
Merged!

**Pull request merged**
